name: Deploy Infra

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        type: choice
        description: "Select Terraform action"
        options:
          - apply
          - destroy
        required: true
  push:
    branches:
      - main
    paths-ignore:
      - 'readme.md'
      - '.github/workflows/app.yml'
      - 'docs/**'
      - 'app/**'

permissions:
  contents: read
  id-token: write

jobs:
  deploy_infra:
    name: Deploy AWS Infra
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v4

      # I'm very heavy on the use of OIDC for AWS authentication
      # My GitHub Account is already connected to my AWS Account through OIDC
      # So I'm just calling the OIDC role to assume in this step
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-north-1
          role-to-assume: role-to-assume:arn:aws:iam::711387141889:role/github-actions-role
          role-session-name: github-${{ github.run_id }}
        
      - name: Verify access
        run: aws sts get-caller-identity


      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan

      - name: Terraform apply
        id: apply
        if: ${{ github.event.inputs.terraform_action == 'apply' }}
        run: terraform apply --auto-approve

      - name: Terraform destroy
        id: destroy
        if: ${{ github.event.inputs.terraform_action == 'destroy' }}
        run: terraform destroy --auto-approve
